### ISSUE TITLE
iron:router's pathFor needs explicit _id=_id

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#10]
the iron-router helper functions like *pathFor* will check for params in current context automaticly. With this it wants to have the params be named (which do break existing code, if you are not aware).

e.g.: for a route like *Router.route('/projects/edit/:_id', {.....});*
~~~html
before
{{pathFor 'projects.edit'}}
now
{{pathFor 'projects.edit' _id=_id}}
~~~

**Comment by quietcreep** [comment]
Was this meant for Formation? I'm not sure how this is applicable.

**Comment by krawalli** [comment]
This is Formation's Model for use with iron-router's pathFor helper. I will dig into code why it works different when Formation Model is not used.

For now its just a kind of reminder until I figured out why.

**Comment by quietcreep** [comment]
Ah, I think I know what's happening. The _id property on ModelInstances are non-enumerable, and I bet IronRouter is iterating over the current context. Because _id is non-enumerable, it won't be iterated over in any loops.  Changing this on my end would break a couple things, so it may just have to stand.

If you'd like to dig around to see if there's a workaround, let me know if you find anything.
