### ISSUE TITLE
widget TextArea does not convert newlines in <br> in view Mode

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#14]
widget TextArea does not convert newlines in <br> in view Mode

**Comment by quietcreep** [comment]
What would you expect that they convert into? The expected behavior should be to ignore most formatting and html tags so that the user can't inject anything insecure.

If you want to ensure new lines don't get ignored, or to accept html or markdown, add the Meteor Markdown package, then put the display mode content between a ```{{# markdown }}```.  I know it's a little more work, but if a dev wants to risk insecure content, it should take a little more work.

**Comment by quietcreep** [comment]
It might be nice to have a widget add-on for a WYSIWYG markdown editor. As in, an external package that you could just plug in...

Have any interest in trying to put one together?

**Comment by krawalli** [comment]
There is a prototype from another project made with *codemirror* to get this effect.

All that needs to be done is to convert \n to <br> when in non-editing mode.

**Comment by quietcreep** [comment]
Can you send some sample code? 

It seems like it would still necessitate either injecting html into the display mode value, or the use of triple curly brace ```{{{ value }}}``` which allows users' content to be parsed and displayed as html, and I'm not  sure that's the best option.

**Comment by krawalli** [comment]
maybe lets try this (see latest answer)
http://stackoverflow.com/questions/22285310/meteor-how-to-render-line-breaks

**Comment by quietcreep** [comment]
Provisionally test this out.  I just added an inline ```style="white-space:pre-wrap"``` to each display <p>.

If it does anything funny on the other fields, let me know.
