### ISSUE TITLE
Securing update / insert

### ISSUE THREAD

**Issue by illmat** [quietcreep/meteor-formation#20]
I'm playing with the demo app and recognized that your allow rules don't apply on the collections.
The editable/savable/removable functions are just used on the server side. I can still remove and save from the client collection.
What's your official way to do secure inserts/updates?

**Comment by krawalli** [comment]
There is a second one with that:
from packages.js
~~~
api.addFiles( "saving.js", both );
~~~
but the source is wrapped in
~~~
if ( Meteor.isServer ){
~~~

so it simply must not be shipped to the client.
I will create a PR for that.

**Comment by quietcreep** [comment]
I'm working on a README file now to explain all these things. This one's a big change that happened recently.  Each model and each field has a ```savable``` param that you can set as a boolean, or as a function that returns a boolean.  Each model also has a ```removable``` param that is set up the same way. Those determine user permission to insert/update/remove.  Also, each model has an ```isNew``` method that will tell you if it's a newInstance to be inserted; you can use that in the savable function to control inserts.

The allow/deny rules in the demo app are left over from when I was making calls to the collection's built-in insert/update/remove; now, though, I'm making calls to custom Meteor.methods, but I haven't updated anything to reflect that :sweat: .  I will be soon, though.

I'm considering mimicking the collection.allow strategy, but I'm not sure how to do that without removing ```savable``` and ```removable``` from models to keep everyone on the same page.

Finally, the reason the savable property throws an exception is because I'm using Object.defineProperty to build models and modelInstances, and by default these properties, once defined, cannot be overwritten.

**Comment by krawalli** [comment]
could there be a fall-back to use the standard allow/deny if savable & co is not defined in model?

**Comment by quietcreep** [comment]
@krawalli That's a great idea. Let's do that.

**Comment by krawalli** [comment]
I will add a +1 to the coffee list :)

**Comment by quietcreep** [comment]
Alright, the most recent commit to formation-core now defaults to collection.allow/deny.

The only challenge is that Meteor recommends calling collection.allow/deny only on the server, which means that it won't be available on the client.  If you call it on both, it doesn't seem to have any side effects, and means that the default savable/removable will actually have something to call.

Let me know if there are any issues with this on your end.
