### ISSUE TITLE
new field type: any or raw

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#23]
for saving some payload attached to a document, there should be a "any" or "raw" field type. There is not expected behavior for display, edit or validation. Just store the object as is.

Would this be possible?

**Comment by quietcreep** [comment]
It should be, but data should be limited to the MongoDB BSON data types (or the Meteor EJSON types for convenience).  Were you thinking Javascript Objects or just anything?

If it's an object, instead of validating for a certain data type, it could "validate" by trying to parse the object into valid EJSON and catching any parsing errors.

Thoughts?

**Comment by krawalli** [comment]
JS object is enough. If it could be parsed, so that no function etc. is inside, thats a cool idea.

**Comment by krawalli** [comment]
That new README helps a lot - Thank you for this.

Any ideas / progress / things I might help on that field type here?

**Comment by quietcreep** [comment]
I'm glad it helped. I'm neck-deep in another project at the moment, so if you'd like to take a stab at this field, I'm more than happy to accept pull requests. Thanks again for all your help thus far!

**Comment by krawalli** [comment]
seems that PR #6 for formation-core covers that feature - Thanks @illmat

**Comment by quietcreep** [comment]
Let's see how everything works. Looks good on first glance!
