### ISSUE TITLE
publish / subscribe

### ISSUE THREAD

**Issue by krawalli** [quietcreep/meteor-formation#5]
What would be the preferred way for "publish/subscribe"?

In the online demo 

~~~js
Ingredients = new Model({
  collection: new Meteor.Collection( 'ingredients' ),
...
~~~

will cause an error in publish function (Exception from sub XYZ Error: Publish function returned an array of non-Cursors), cause Ingredients.find() will return the Model, not the Meteor.Collection.

A possible workaround is to seperate the collection so 
~~~js
Igdnts = new Meteor.Collection( 'ingredients' );

Ingredients = new Model({
  collection: Igdnts,
...
~~~

and use Igdnts.find() in the publish fundtion.

Maybe you could add a wrapper for publish so it becomes much easier.

However: Thank you for your package - nice work so far i can tell.

PS: Will you accept pull request for this project?

**Comment by quietcreep** [comment]
Hrm, my approach when using this package has always been

```javascript
Meteor.publish( 'ingredients', function(){
  return Ingredients.collection.find();
})
```

On the client, the call to ```Ingredients.find()``` does ```Ingredients.collection.find().fetch()```, then iterates over the resulting list to instantiate new ModelInstances.

I've been fairly careful to make sure no more data than necessary goes over the wire, so when I send cursors or objects from server to client or vice versa, it's always in the form of a Javascript Object, not a ModelInstance or array of them.

It would be interesting to have a context-aware ``Model.find()`` call, so that it would automatically know to send over a cursor rather than an array of ModelInstances, but I'm not quite sure how that would be done without changing the method signature.

A wrapper function could work, but I'd prefer that it's usage be as close to Meteor.publish as possible.

Thanks, and yes, I'll definitely look at pull requests if you've got ideas.

**Comment by krawalli** [comment]
the .collection. approach is effective enough.
I just ran into that trap. The demo-app is not published on github? That would help to start on use in own projects.

**Comment by quietcreep** [comment]
Yeah... the documentation is in need of work; I'll see what I can put together in the next few days.  

Good idea about the demo app, I'll add it to this repo when I get the chance.
