### ISSUE TITLE
Having issues integrating formation with user profile

### ISSUE THREAD

**Issue by rvanhoepen** [quietcreep/meteor-formation#8]
Hey quietcreep,
Thanks the revert on cancel is working perfectly.
I wanted to say that your package reminds me a lot about my Django days :smile: 
At the moment I have some issues integrating formation.

I would like to use formation as a way for users to edit their profile information.
I have a publish and a subscribe already, but tried following along your code examples on
formation.meteor.com

I am using the standard Meteor.users collection for the user

I have the following at /lib/forms/profile.js
```js
var Model = Formation.Model;
var Fields = Formation.Fields;

Profile = new Model({
    collection: Meteor.users,
    schema: {
        username: new Fields.Char({ max: 140, editable: true }),
        email: new Fields.Email({ max: 140, editable: true }),
        first_name: new Fields.Char({ max: 50, editable: true }),
        last_name: new Fields.Char({ max: 50, editable: true })
    }
});
```
and then in /client/templates/profile/profile.js
```js
Template.ProfileEdit.helpers({
    userProfile: function() {
        return Profile.findOne();
    }
});
```
and then I tried implementing the html as follows:
```html
<form class="form-horizontal" role="form">
      {{> dxField username}}
      {{> dxField emails.[0].address}}
      {{> dxField profile.first_name}}
      {{> dxField profile.last_name}}
      {{> dxButtons}}
</form>
```

I know there are errors in the code above, would like to hear your input
as the package author how would you have implemented this?

I left out the summary part, as I don't want a summary of the form, is
it in any way necessary?

Sorry about the long post

**Comment by krawalli** [comment]
For me as non-author it looks like i would do it.
Your schema must reflect the basic requirements for a users entry otherwise a update or insert would fail.
If you made this one running you should add it to the README or Documentation, since this is reusable for many others.

**Comment by quietcreep** [comment]
So, seems like a README is in order ASAP.

I see a couple things.  Shouldn't it be ```{{> dxField emails.0.address}}``` instead of ```{{> dxField emails.[0].address}}``` in a template?

Also, there's a helper called dxArray you can use to handle array objects.  It's pretty much an #each tag with an "Add" button.

Here are two things you could do:
```Handlebars
<form class="form-horizontal" role="form">
  {{> dxField username}}
  {{# each emails }}
    {{> dxField address}}
  {{/ each }}
  {{> dxField profile.first_name}}
  {{> dxField profile.last_name}}
  {{> dxButtons}}
</form> 
```

Or:
```Handlebars
<form class="form-horizontal" role="form">
  {{> dxField username}}
  {{# dxArray field='emails' model=this }}
    {{> dxField address}}
  {{/ each }}
  {{> dxField profile.first_name}}
  {{> dxField profile.last_name}}
  {{> dxButtons}}
</form> 
```

No need for the summary; that's just handy to have for displaying fields / forms in non-edit mode.

**Comment by rvanhoepen** [comment]
Thanks for the responses @krawalli and @quietcreep , will quickly see if this fixes everything.
@quietcreep if I use a {{# each emails }} then surely if the array is currently empty it won't display
anything?

Does the package support cases where there might not be any values in the fields, yet?
I'm not asking users at sign up for their first and last names for example.

**Comment by quietcreep** [comment]
@krawalli it depends; I think Model comes stock with 1 as the extra param.

So that means when you have a nested Model in an array (like Users.emails), if emails is empty, it will add a new Instance just in case you'd like to use it. So, that first time you ask for first_name and last_name, there should be an empty model there.

If there isn't, you can add an extra in the Model
```javascript
Users = Model({
  collection: Meteor.users,
  schema: {
    emails: [ Model({
      schema: {...},
      extra: 1,
    }) ]
});
```

If you use the {{> dxArray }} helper, there should be an "add" button automatically inserted for adding new nested ModelInstances.  Otherwise you can add new instances manually in your template helpers by doing 
```javascript
var newEmail = new Users.emails[0].newInstance
```
